package com.infobip.mobilemessaging.huawei.plugin

internal object ChannelContract {
    const val METHOD_CHANNEL = "com.infobip.mobilemessaging.huawei/methods"
    const val EVENT_CHANNEL = "com.infobip.mobilemessaging.huawei/events"
    const val INITIALIZE = "initialize"
    const val SET_REGISTRATION = "setRegistration"
    const val IS_REGISTRATION_ENABLED = "isRegistrationEnabled"
    const val APPLICATION_CODE = "applicationCode"
    const val ENABLED = "enabled"
    const val GET_USER = "getUser"
    const val FETCH_USER = "fetchUser"
    const val SAVE_USER = "saveUser"
    const val PERSONALIZE = "personalize"
    const val DEPERSONALIZE = "depersonalize"
    const val USER = "user"
    const val USER_IDENTITY = "userIdentity"
    const val USER_ATTRIBUTES = "userAttributes"
    const val FORCE_DEPERSONALIZE = "forceDepersonalize"
    const val EXTERNAL_USER_ID = "externalUserId"
    const val FIRST_NAME = "firstName"
    const val LAST_NAME = "lastName"
    const val MIDDLE_NAME = "middleName"
    const val GENDER = "gender"
    const val BIRTHDAY = "birthday"
    const val PHONES = "phones"
    const val EMAILS = "emails"
    const val TAGS = "tags"
    const val CUSTOM_ATTRIBUTES = "customAttributes"

    const val EVENT_VERSION = 1
    const val MESSAGE_RECEIVED = "message_received"
    const val NOTIFICATION_TAPPED = "notification_tapped"
    const val NOTIFICATION_ACTION_TAPPED = "notification_action_tapped"
    const val REGISTRATION_UPDATED = "registration_updated"
}
