abstract final class ChannelContract {
  static const methodChannel = 'com.infobip.mobilemessaging.huawei/methods';
  static const eventChannel = 'com.infobip.mobilemessaging.huawei/events';
  static const initialize = 'initialize';
  static const setRegistration = 'setRegistration';
  static const isRegistrationEnabled = 'isRegistrationEnabled';
  static const applicationCode = 'applicationCode';
  static const enabled = 'enabled';
  static const getUser = 'getUser';
  static const fetchUser = 'fetchUser';
  static const saveUser = 'saveUser';
  static const personalize = 'personalize';
  static const depersonalize = 'depersonalize';
  static const user = 'user';
  static const userIdentity = 'userIdentity';
  static const userAttributes = 'userAttributes';
  static const forceDepersonalize = 'forceDepersonalize';
  static const externalUserId = 'externalUserId';
  static const firstName = 'firstName';
  static const lastName = 'lastName';
  static const middleName = 'middleName';
  static const gender = 'gender';
  static const birthday = 'birthday';
  static const phones = 'phones';
  static const emails = 'emails';
  static const tags = 'tags';
  static const customAttributes = 'customAttributes';
  static const customValueType = '__infobipType';
  static const customValue = 'value';
  static const customDateType = 'date';

  static const eventVersion = 1;
  static const messageReceived = 'message_received';
  static const notificationTapped = 'notification_tapped';
  static const notificationActionTapped = 'notification_action_tapped';
  static const registrationUpdated = 'registration_updated';
}
